import { DatabaseSchema, Goal, Habit, JournalEntry, FocusSession } from "./types";
import { hashPassword } from "./auth";

export function getIsoDateOffset(daysOffset: number): string {
  const d = new Date();
  d.setDate(d.getDate() + daysOffset);
  return d.toISOString().split("T")[0];
}

export function calculateLevel(xp: number): number {
  return Math.max(1, Math.floor(xp / 500) + 1);
}

export function createStarterDataForNewUser(userId: string): {
  habits: Habit[];
  goals: Goal[];
  journals: JournalEntry[];
  focusSessions: FocusSession[];
} {
  const today = getIsoDateOffset(0);
  const in25Days = getIsoDateOffset(25);
  const in60Days = getIsoDateOffset(60);

  const habits: Habit[] = [
    {
      id: `hab_${userId}_1`,
      userId,
      title: "90-Minute Unbroken Deep Work Block",
      description: "Zero phone, zero notifications. Build your highest-leverage project first thing.",
      pillar: "Craft",
      xpReward: 50,
      targetDaysPerWeek: 6,
      completedDates: [today],
      streak: 1,
      createdAt: new Date().toISOString(),
    },
    {
      id: `hab_${userId}_2`,
      userId,
      title: "45-Min Strength or Zone-2 Conditioning",
      description: "Train the physical vessel daily. Resistance training or high-output cardio.",
      pillar: "Body",
      xpReward: 45,
      targetDaysPerWeek: 5,
      completedDates: [],
      streak: 0,
      createdAt: new Date().toISOString(),
    },
    {
      id: `hab_${userId}_3`,
      userId,
      title: "20 Pages High-Signal Reading / Study",
      description: "Philosophy, systems thinking, biography, or technical mastery before sleep.",
      pillar: "Mind",
      xpReward: 35,
      targetDaysPerWeek: 7,
      completedDates: [],
      streak: 0,
      createdAt: new Date().toISOString(),
    },
    {
      id: `hab_${userId}_4`,
      userId,
      title: "Evening Stoic Audit & Next-Day Architecture",
      description: "Review daily execution, log 1 win & 1 lesson, lock top 3 priorities for tomorrow.",
      pillar: "Spirit",
      xpReward: 30,
      targetDaysPerWeek: 7,
      completedDates: [],
      streak: 0,
      createdAt: new Date().toISOString(),
    },
  ];

  const goals: Goal[] = [
    {
      id: `goal_${userId}_1`,
      userId,
      title: "Complete My First 25-Day Evolution Sprint",
      description: "Execute daily core habits with >85% consistency over the next 25 days.",
      pillar: "Mind",
      targetDate: in25Days,
      priority: "Core",
      status: "active",
      progress: 25,
      xpReward: 500,
      milestones: [
        { id: `ms_${userId}_1`, title: "Set up personal growth command center & core habits", completed: true },
        { id: `ms_${userId}_2`, title: "Complete 7 consecutive days of morning deep work", completed: false },
        { id: `ms_${userId}_3`, title: "Log 10 hours of tracked focus sessions", completed: false },
        { id: `ms_${userId}_4`, title: "Finish all 25 days & share breakthrough in The Arena", completed: false },
      ],
      createdAt: new Date().toISOString(),
    },
    {
      id: `goal_${userId}_2`,
      userId,
      title: "Ship Flagship Personal or Career Project",
      description: "Design, build, and launch a high-impact deliverable that levels up my craft and leverage.",
      pillar: "Craft",
      targetDate: in60Days,
      priority: "High",
      status: "active",
      progress: 0,
      xpReward: 750,
      milestones: [
        { id: `ms_${userId}_5`, title: "Define scope, architecture, and success metrics", completed: false },
        { id: `ms_${userId}_6`, title: "Build core MVP in 14 deep work sessions", completed: false },
        { id: `ms_${userId}_7`, title: "Publish publicly and gather real feedback", completed: false },
      ],
      createdAt: new Date().toISOString(),
    },
  ];

  const journals: JournalEntry[] = [
    {
      id: `jrn_${userId}_1`,
      userId,
      date: today,
      title: "Day 1: Entering ProjectAlex25",
      winOfTheDay: "Committed to structured daily execution and initialized my personal growth architecture.",
      lessonLearned: "Clarity precedes mastery—when the system is visible, friction disappears.",
      gratitude: "Grateful for the opportunity and discipline to build a stronger version of myself.",
      content: "Today marks the start of my ProjectAlex25 journey. Focus is locked on consistent daily habits across Mind, Body, Craft, Wealth, and Spirit.",
      mood: 5,
      energy: 5,
      pillar: "Mind",
      tags: ["Day1", "Protocol25", "Clarity"],
      createdAt: new Date().toISOString(),
    },
  ];

  const focusSessions: FocusSession[] = [
    {
      id: `foc_${userId}_1`,
      userId,
      taskTitle: "Initial Life & Goal Architecture Setup",
      pillar: "Mind",
      durationMinutes: 25,
      xpEarned: 50,
      completedAt: new Date().toISOString(),
    },
  ];

  return { habits, goals, journals, focusSessions };
}

export function createInitialSeedDatabase(): DatabaseSchema {
  const today = getIsoDateOffset(0);
  const d1 = getIsoDateOffset(-1);
  const d2 = getIsoDateOffset(-2);
  const d3 = getIsoDateOffset(-3);
  const d4 = getIsoDateOffset(-4);
  const d5 = getIsoDateOffset(-5);
  const d6 = getIsoDateOffset(-6);

  const demoPassHash = hashPassword("password123");

  return {
    users: [
      {
        id: "usr_alex25",
        name: "Alex Mercer",
        email: "alex@projectalex25.com",
        handle: "alex25",
        passwordHash: demoPassHash,
        avatarColor: "from-amber-400 to-orange-600",
        bio: "Founder & Architect at ProjectAlex25. Building sovereign discipline across Mind, Body, Craft, Wealth & Spirit.",
        primaryPillar: "Craft",
        xp: 5840,
        level: 12,
        streak: 18,
        lastActiveDate: today,
        focusMinutesTotal: 1420,
        dailyFocusTarget: 120,
        joinedAt: getIsoDateOffset(-45),
        badges: ["Protocol 25 Founder", "14-Day Streak", "Deep Work Centurion", "Apex Architect"],
      },
      {
        id: "usr_elena",
        name: "Elena Vance",
        email: "elena@projectalex25.com",
        handle: "elena_vanguard",
        passwordHash: demoPassHash,
        avatarColor: "from-emerald-400 to-teal-600",
        bio: "Quant researcher & endurance athlete. 05:00 club. Executing Monk Mode Sprint.",
        primaryPillar: "Mind",
        xp: 6450,
        level: 13,
        streak: 24,
        lastActiveDate: today,
        focusMinutesTotal: 1890,
        dailyFocusTarget: 150,
        joinedAt: getIsoDateOffset(-60),
        badges: ["Monk Mode Master", "21-Day Streak", "Iron Mind"],
      },
      {
        id: "usr_marcus",
        name: "Marcus Thorne",
        email: "marcus@projectalex25.com",
        handle: "marcus_stoic",
        passwordHash: demoPassHash,
        avatarColor: "from-sky-400 to-indigo-600",
        bio: "Full-stack builder & daily powerlifter. Memento Mori. Zero excuses.",
        primaryPillar: "Body",
        xp: 4920,
        level: 10,
        streak: 15,
        lastActiveDate: today,
        focusMinutesTotal: 1120,
        dailyFocusTarget: 90,
        joinedAt: getIsoDateOffset(-35),
        badges: ["Kinetic Titan", "14-Day Streak"],
      },
      {
        id: "usr_kai",
        name: "Kai Nakamura",
        email: "kai@projectalex25.com",
        handle: "kai_deepwork",
        passwordHash: demoPassHash,
        avatarColor: "from-purple-400 to-fuchsia-600",
        bio: "AI Systems Engineer. 4 hours of pure deep work before noon every single day.",
        primaryPillar: "Craft",
        xp: 4310,
        level: 9,
        streak: 11,
        lastActiveDate: d1,
        focusMinutesTotal: 1650,
        dailyFocusTarget: 180,
        joinedAt: getIsoDateOffset(-28),
        badges: ["Deep Work Centurion", "7-Day Streak"],
      },
      {
        id: "usr_aria",
        name: "Aria Sterling",
        email: "aria@projectalex25.com",
        handle: "aria_sovereign",
        passwordHash: demoPassHash,
        avatarColor: "from-rose-400 to-pink-600",
        bio: "Creative Director & angel investor. Designing a high-leverage, intentional life.",
        primaryPillar: "Wealth",
        xp: 3790,
        level: 8,
        streak: 9,
        lastActiveDate: today,
        focusMinutesTotal: 940,
        dailyFocusTarget: 90,
        joinedAt: getIsoDateOffset(-22),
        badges: ["Sovereign Builder"],
      },
    ],
    habits: [
      {
        id: "hab_demo_1",
        userId: "usr_alex25",
        title: "90-Min Morning Deep Work (Zero Distractions)",
        description: "First 90 minutes of the day dedicated strictly to shipping flagship code & strategy.",
        pillar: "Craft",
        xpReward: 50,
        targetDaysPerWeek: 6,
        completedDates: [d6, d5, d4, d3, d2, d1, today],
        streak: 7,
        createdAt: getIsoDateOffset(-30),
      },
      {
        id: "hab_demo_2",
        userId: "usr_alex25",
        title: "Heavy Hypertrophy / Zone-2 Conditioning",
        description: "60 minutes of structured strength training or outdoor Zone-2 run.",
        pillar: "Body",
        xpReward: 45,
        targetDaysPerWeek: 5,
        completedDates: [d6, d5, d3, d2, d1, today],
        streak: 4,
        createdAt: getIsoDateOffset(-30),
      },
      {
        id: "hab_demo_3",
        userId: "usr_alex25",
        title: "30 Pages High-Signal Reading (No Screens)",
        description: "Deep reading in systems architecture, philosophy, or cognitive science.",
        pillar: "Mind",
        xpReward: 35,
        targetDaysPerWeek: 7,
        completedDates: [d5, d4, d3, d2, d1],
        streak: 5,
        createdAt: getIsoDateOffset(-30),
      },
      {
        id: "hab_demo_4",
        userId: "usr_alex25",
        title: "Capital Allocation & Revenue Leverage Audit",
        description: "Track cashflow, review high-ROI distribution metrics, and compound digital assets.",
        pillar: "Wealth",
        xpReward: 40,
        targetDaysPerWeek: 5,
        completedDates: [d6, d4, d2, d1, today],
        streak: 3,
        createdAt: getIsoDateOffset(-25),
      },
      {
        id: "hab_demo_5",
        userId: "usr_alex25",
        title: "15-Min Stoic Breathwork & Evening Reflection",
        description: "Decompress the nervous system, practice gratitude, and lock tomorrow's top 3 objectives.",
        pillar: "Spirit",
        xpReward: 30,
        targetDaysPerWeek: 7,
        completedDates: [d6, d5, d4, d3, d2, d1],
        streak: 6,
        createdAt: getIsoDateOffset(-25),
      },
    ],
    goals: [
      {
        id: "goal_demo_1",
        userId: "usr_alex25",
        title: "Launch ProjectAlex25 v2.0 Global Platform",
        description: "Ship the full-stack Next.js personal growth command center on Vercel with auth, habit matrix, and community arena.",
        pillar: "Craft",
        targetDate: getIsoDateOffset(14),
        priority: "Core",
        status: "active",
        progress: 75,
        xpReward: 1000,
        milestones: [
          { id: "m_1", title: "Architect backend API & persistent data engine", completed: true },
          { id: "m_2", title: "Build authentication, JWT sessions, and user onboarding", completed: true },
          { id: "m_3", title: "Launch interactive 5-Pillar Habit Matrix & Deep Work Timer", completed: true },
          { id: "m_4", title: "Scale to 1,000 active members on Vercel production", completed: false },
        ],
        createdAt: getIsoDateOffset(-20),
      },
      {
        id: "goal_demo_2",
        userId: "usr_alex25",
        title: "Sub-18 Minute 5K + 225lb Overhead Press",
        description: "Attain hybrid athletic peak combining explosive strength with elite aerobic capacity.",
        pillar: "Body",
        targetDate: getIsoDateOffset(45),
        priority: "High",
        status: "active",
        progress: 50,
        xpReward: 800,
        milestones: [
          { id: "m_5", title: "Establish 5x/week hybrid strength + Zone-2 split", completed: true },
          { id: "m_6", title: "Hit sub-19:00 5K benchmark time trial", completed: true },
          { id: "m_7", title: "Strict press 205lb for 3 clean reps", completed: false },
          { id: "m_8", title: "Complete final peak test week", completed: false },
        ],
        createdAt: getIsoDateOffset(-30),
      },
      {
        id: "goal_demo_3",
        userId: "usr_alex25",
        title: "Publish 12 Deep-Dive Essays on High-Performance Systems",
        description: "Distill mental models on cognitive endurance, focus architecture, and asymmetric leverage.",
        pillar: "Mind",
        targetDate: getIsoDateOffset(30),
        priority: "Medium",
        status: "active",
        progress: 67,
        xpReward: 600,
        milestones: [
          { id: "m_9", title: "Outline 12 core mental models & thesis frameworks", completed: true },
          { id: "m_10", title: "Publish Essays #1 through #8", completed: true },
          { id: "m_11", title: "Publish Essays #9 through #12 & compile anthology", completed: false },
        ],
        createdAt: getIsoDateOffset(-25),
      },
    ],
    journals: [
      {
        id: "jrn_demo_1",
        userId: "usr_alex25",
        date: today,
        title: "Velocity Through Ruthless Simplification",
        winOfTheDay: "Completed 110 minutes of unbroken architecture work before 8:30 AM and crushed leg day.",
        lessonLearned: "Every open loop in your environment steals 10% of your cognitive RAM. Close loops immediately.",
        gratitude: "Grateful for a sharp mind, strong health, and a community of builders who refuse mediocrity.",
        content: "Entered flow state within 8 minutes of starting the morning session today. Eliminating phone checks for the first two hours after waking remains the single highest-ROI protocol in my stack.",
        mood: 5,
        energy: 5,
        pillar: "Craft",
        tags: ["DeepWork", "Protocol25", "FlowState"],
        createdAt: new Date().toISOString(),
      },
      {
        id: "jrn_demo_2",
        userId: "usr_alex25",
        date: d2,
        title: "The Compounding Effect of Tiny Standards",
        winOfTheDay: "Maintained 100% habit adherence despite a packed travel and meeting schedule.",
        lessonLearned: "Never miss twice. Even a 20-minute condensed session keeps the identity intact.",
        gratitude: "Evening cold walk cleared my head completely.",
        content: "When energy dips, rely on protocol—not motivation. Motivation is weather; systems are climate.",
        mood: 4,
        energy: 4,
        pillar: "Mind",
        tags: ["Stoicism", "Consistency", "Discipline"],
        createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
      },
    ],
    focusSessions: [
      {
        id: "foc_demo_1",
        userId: "usr_alex25",
        taskTitle: "ProjectAlex25 Full-Stack Engine Architecture",
        pillar: "Craft",
        durationMinutes: 50,
        xpEarned: 100,
        completedAt: new Date(Date.now() - 3600000 * 3).toISOString(),
      },
      {
        id: "foc_demo_2",
        userId: "usr_alex25",
        taskTitle: "Systems Thinking & Cognitive Models Synthesis",
        pillar: "Mind",
        durationMinutes: 45,
        xpEarned: 90,
        completedAt: new Date(Date.now() - 86400000).toISOString(),
      },
      {
        id: "foc_demo_3",
        userId: "usr_alex25",
        taskTitle: "Q4 Strategic Capital & Product Roadmap",
        pillar: "Wealth",
        durationMinutes: 25,
        xpEarned: 50,
        completedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
      },
    ],
    challenges: [
      {
        id: "chl_protocol25",
        title: "Protocol 25: The Core Evolution",
        subtitle: "The signature 25-day total life recalibration protocol",
        description: "25 consecutive days of uncompromising execution across all 5 Pillars. Designed to rewire baseline discipline, eliminate cheap dopamine, and ship meaningful work.",
        durationDays: 25,
        pillar: "Mind",
        difficulty: "Vanguard",
        xpReward: 1250,
        rules: [
          "90 minutes of distraction-free Deep Work before checking social feeds",
          "45+ minutes of intentional physical training or Zone-2 cardio daily",
          "Zero ultra-processed sugar or late-night doomscrolling",
          "20 pages of high-signal reading + evening Stoic journal audit",
        ],
        participantsCount: 342,
        userProgress: [
          {
            userId: "usr_alex25",
            completedDays: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
            startedAt: getIsoDateOffset(-18),
          },
        ],
      },
      {
        id: "chl_monkmode30",
        title: "Monk Mode: Deep Craft Sprint",
        subtitle: "30 days of extreme creative & technical output",
        description: "Isolate your highest-value objective and dedicate 30 days of surgical focus to shipping it. Built for founders, engineers, creators, and operators.",
        durationDays: 30,
        pillar: "Craft",
        difficulty: "Apex",
        xpReward: 1800,
        rules: [
          "Minimum 2 Deep Work blocks (50+ mins each) logged daily",
          "Phone stored in another room during all focus blocks",
          "Daily ship log: commit code, write pages, or ship tangible progress",
          "Strict sleep hygiene: 7.5+ hours in bed at consistent times",
        ],
        participantsCount: 218,
        userProgress: [
          {
            userId: "usr_alex25",
            completedDays: [1, 2, 3, 4, 5, 6, 7, 8],
            startedAt: getIsoDateOffset(-8),
          },
        ],
      },
      {
        id: "chl_kinetictemple",
        title: "Kinetic Temple: 25-Day Hybrid Conditioning",
        subtitle: "Forge elite physical energy, posture, and metabolic resilience",
        description: "Your cognitive output is upstream of your biology. Spend 25 days upgrading strength, VO2 max, hydration, and recovery.",
        durationDays: 25,
        pillar: "Body",
        difficulty: "Vanguard",
        xpReward: 1100,
        rules: [
          "Hit daily protein & 3.5L+ hydration + electrolytes target",
          "10,000+ steps + structured resistance or endurance session",
          "Morning sunlight viewing within 30 minutes of waking",
          "Zero alcohol for the entire 25-day block",
        ],
        participantsCount: 189,
        userProgress: [],
      },
      {
        id: "chl_sovereign21",
        title: "Sovereign Mind & Dopamine Reset",
        subtitle: "21 days to reclaim attention span and inner stillness",
        description: "Reset overstimulated reward pathways so hard work feels effortless and rewarding again.",
        durationDays: 21,
        pillar: "Spirit",
        difficulty: "Initiate",
        xpReward: 900,
        rules: [
          "No short-form video feeds (TikTok, Reels, Shorts) for 21 days",
          "15 minutes of daily breathwork, meditation, or silent walk",
          "Write down 3 gratitudes and 1 lesson every evening",
          "Single-tasking only: one browser tab group, one objective at a time",
        ],
        participantsCount: 415,
        userProgress: [],
      },
    ],
    posts: [
      {
        id: "pst_1",
        userId: "usr_elena",
        authorName: "Elena Vance",
        authorHandle: "elena_vanguard",
        authorLevel: 13,
        authorAvatarColor: "from-emerald-400 to-teal-600",
        authorPillar: "Mind",
        content: "Day 24 of Protocol 25 locked in. 2.5 hours of quantitative modeling before sunrise followed by a 10K tempo run. When you remove negotiation from your morning routine, your output doubles.",
        tag: "Protocol",
        likes: ["usr_alex25", "usr_marcus", "usr_kai"],
        comments: [
          {
            id: "cmt_1",
            userId: "usr_alex25",
            authorName: "Alex Mercer",
            authorHandle: "alex25",
            content: "Relentless execution Elena. One more day to complete the full 25-day circuit!",
            createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
          },
        ],
        createdAt: new Date(Date.now() - 3600000 * 4).toISOString(),
      },
      {
        id: "pst_2",
        userId: "usr_alex25",
        authorName: "Alex Mercer",
        authorHandle: "alex25",
        authorLevel: 12,
        authorAvatarColor: "from-amber-400 to-orange-600",
        authorPillar: "Craft",
        content: "Welcome to the new ProjectAlex25 Command Center. Built for everyone ready to track their 5 Pillars (Mind, Body, Craft, Wealth, Spirit), lock in 25-day protocols, and compound daily wins together.",
        tag: "Milestone",
        likes: ["usr_elena", "usr_marcus", "usr_kai", "usr_aria"],
        comments: [
          {
            id: "cmt_2",
            userId: "usr_marcus",
            authorName: "Marcus Thorne",
            authorHandle: "marcus_stoic",
            content: "The new Deep Work timer + Habit Matrix is clean. Let's get after it.",
            createdAt: new Date(Date.now() - 3600000 * 5).toISOString(),
          },
        ],
        createdAt: new Date(Date.now() - 3600000 * 8).toISOString(),
      },
      {
        id: "pst_3",
        userId: "usr_marcus",
        authorName: "Marcus Thorne",
        authorHandle: "marcus_stoic",
        authorLevel: 10,
        authorAvatarColor: "from-sky-400 to-indigo-600",
        authorPillar: "Body",
        content: "Hit a 15-day unbroken streak on both Heavy Conditioning and Stoic Evening Audit. Small daily disciplines compound into unrecognizable transformation over 90 days.",
        tag: "Streak",
        likes: ["usr_alex25", "usr_aria"],
        comments: [],
        createdAt: new Date(Date.now() - 3600000 * 14).toISOString(),
      },
    ],
  };
}
